export const LOCAL_STORAGE_EVM_PUBLIC_ADDRESS =
  "LOCAL_STORAGE_EVM_PUBLIC_ADDRESS";
export const LOCAL_STORAGE_EVM_WALLET_MNEMONIC =
  "LOCAL_STORAGE_EVM_WALLET_MNEMONIC";

export const LOCAL_STORAGE_ICP_PUBLIC_ADDRESS =
  "LOCAL_STORAGE_ICP_PUBLIC_ADDRESS";
export const LOCAL_STORAGE_ICP_WALLET_MNEMONIC =
  "LOCAL_STORAGE_ICP_WALLET_MNEMONIC";

export const LOCAL_STORAGE_ALIAS_NICKNAME = "LOCAL_STORAGE_ALIAS_NICKNAME";
export const LOCAL_STORAGE_ONBOARDING_CHECKPOINT =
  "LOCAL_STORAGE_ONBOARDING_CHECKPOINT";

export const LOCAL_STORAGE_ICP_CANISTER_DRIVE_ID =
  "LOCAL_STORAGE_ICP_CANISTER_DRIVE_ID";

export const CONSTANTS = {
  LOCAL_STORAGE_EVM_PUBLIC_ADDRESS,
  LOCAL_STORAGE_EVM_WALLET_MNEMONIC,
  LOCAL_STORAGE_ICP_PUBLIC_ADDRESS,
  LOCAL_STORAGE_ICP_WALLET_MNEMONIC,
  LOCAL_STORAGE_ALIAS_NICKNAME,
  LOCAL_STORAGE_ONBOARDING_CHECKPOINT,
  LOCAL_STORAGE_ICP_CANISTER_DRIVE_ID,
};

export const ONBOARDING_CHECKPOINTS = {
  FRESH_USER: "FRESH_USER",
  SAMPLE_FILES_LOADED: "SAMPLE_FILES_LOADED",
};

// [TEMP]
export const FACTORY_CANISTER_ID = "jjx63-5iaaa-aaaak-ao7xq-cai";
// export const FACTORY_CANISTER_ID =
//   window.location.origin === "http://localhost:5173"
//     ? "bkyz2-fmaaa-aaaaa-qaaaq-cai"
//     : "jjx63-5iaaa-aaaak-ao7xq-cai";
